version: '3.8'
services:
  db:
    container_name: ${CONTAINER_NAME}
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
      - MYSQL_PASSWORD=$PASSWORD
      - MYSQL_USER=$MYSQL_USER
    ports:
      - '${PORT}:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local